import { cn } from "@/lib/classes";
import type { VariantProps } from "cva";
import { cva } from "cva";
import type { HTMLAttributes } from "react";

/* 
  ============================================================= 
  NB! We use mdx.css instead of proseVariants below.
  Why? [&_selector]:class syntax is unreadable + hard to write, and CSS 
  @apply fails fast on invalid utilities while CVA silently fails.
  See: docs/251218-mdx-styling-learnings.md
  ============================================================= 
*/

/*
  mdx-prose: The Single Source of Truth for MDX Styling

  Responsibility: ALL MDX styling lives here. mdx-components.tsx handles
  only JSX mapping and logic (no styling except HeadingWithId).

  Organization: Styles are chunked into named arrays for readability,
  then spread into proseVariants.

  Toggle USE_CSS_STYLES to switch between:
  - true: Use mdx.css (cleaner, more readable)
  - false: Use proseVariants (JS-based, can import utilities)

  Mental model: docs/251218-mdx-styling-system.md
*/

// Toggle: true = use mdx.css, false = use proseVariants below
const USE_CSS_STYLES = true;

// LAYOUT
// Container width, padding, base spacing
const proseLayout = [
  "Prose px-inset space-y-2.5 group",
  "[&>:not([data-component=Zoomable])]:max-w-(--container-text) [&>*]:mx-auto",
  "[&>a]:block",
];

// INLINE ELEMENTS
// strong, em, span (MDX highlight syntax)
const proseInlineElements = [
  "[&_strong]:font-medium",
  "[&_em]:not-italic",
  "[&_p>span]:font-medium",
];

// LINKS
// Note: When USE_CSS_STYLES=false, links use the "link" class directly
// (textVariants import removed to avoid circular dependency with text.tsx)
const proseLinks = ["[&_a]:link"];

// ZOOMABLE ORCHESTRATION
// Sibling spacing relationships for media components
const proseZoomable = [
  "[&>[data-component=Zoomable]+[data-component=Zoomable]]:pt-0",
  "[&>[data-component=Zoomable]+h2]:mt-w4",
  "[&>[data-component=Zoomable]+h3]:mt-w4",
];

// HEADING SPACING
// Rules for heading sibling relationships
const proseHeadings = ["[&>h2+h3]:!mt-w4"];

// MEDIA OVERRIDES
// button > MediaFigure edge cases
const proseMedia = [
  "[&_button:first-child>.MediaFigure]:pt-0",
  "[&_button+button]:!mt-0",
];

// CODE
// Styles for highlight() output and inline code.
// Must be parent-targeted because we don't control the generated HTML.
const proseCode = [
  "[&_code]:text-[0.925em] [&_code]:tracking-[-0.025em] [&_code]:font-mono",
  "[&_code]:bg-background-active [&_code]:px-[2px] [&_code]:rounded-soft",
  "[&_code>span]:relative [&_code>span]:top-[-0.02em]",
  // Reset when wrapped in pre element
  "[&_[data-component=pre]_code>span]:static [&_[data-component=pre]_code]:text-[0.825em] [&_[data-component=pre]_code]:tracking-[0]",
];

// PRE (code blocks)
const prosePreStyles = [
  "[&_.Pre]:bg-background [&_.Pre]:rounded-button [&_.Pre]:overflow-auto",
  "[&_.Pre_code]:block [&_.Pre_code]:overflow-auto [&_.Pre_code]:py-2.5 [&_.Pre_code]:pl-3",
  "[&_.Pre_code]:hide-scrollbar [&_.Pre_code]:leading-[1.6]",
  "[&_.Pre_code]:bg-transparent",
  // Wrapper div spacing
  "[&_[data-component=pre]]:py-1",
];

// BLOCKQUOTE
const proseBlockquote = [
  "[&_blockquote]:group [&_blockquote]:py-1.5",
  "[&_blockquote_p]:text-fill-light",
  "[&_blockquote_p]:border-border-hover [&_blockquote_p]:border-l [&_blockquote_p]:pb-0 [&_blockquote_p]:pl-2.5 md:[&_blockquote_p]:pl-4",
  "[&_blockquote_strong]:text-meta [&_blockquote_strong]:table [&_blockquote_strong]:pt-[calc(6/16*1em)] [&_blockquote_strong]:!font-normal",
];

// LISTS (ul)
const proseListStyles = [
  "[&_ul]:list-bullets",
  "[&_ol]:list-decimal [&_ol]:space-y-0.5 [&_ol]:pl-5",
];

// CALLOUT
const proseCalloutStyles = [
  "[&_.Callout]:bg-accent3/[0.15] [&_.Callout]:md:pr-w12",
  "[&_.Callout]:rounded-button [&_.Callout]:space-y-1.5 [&_.Callout]:px-3 [&_.Callout]:pt-2.5 [&_.Callout]:pb-2.5",
  "[&_.Callout]:not-first:mt-w4",
  "[&_.Callout_code]:bg-black-a1 [&_.Callout_ul]:text-[0.925em]",
  "[&_.Callout>*]:text-meta",
];

// NOTE
const proseNoteStyles = [
  "[&_.Note]:!mt-w12 [&_.Note]:space-y-2 [&_.Note]:text-meta [&_.Note]:text-solid [&_.Note]:link-block",
  "[&_.Note_p]:text-meta [&_.Note_p]:text-solid",
  "[&_.Note+.Note]:!mt-2",
  "[&_.Note+.footnotes]:!mt-2",
];

// HR (uses Note styling)
const proseHrStyles = ["[&_hr]:border-0"];

// H4
const proseH4Styles = ["[&_h4]:font-bold"];

// CONTACTS
const proseContactsStyles = [
  "[&_[data-component=contacts]]:pt-0.5 [&_[data-component=contacts]]:!pl-0",
];

// FOOTNOTES
// Generated by remark-gfm, we can't wrap these elements.
// Includes scroll margins, backref icon styling, etc.
const proseFootnotes = [
  "[&_#footnotes]:hidden",
  "[&_.footnotes]:text-solid [&_.footnotes]:link-block",
  "[&_.footnotes_p]:text-meta [&_.footnotes_::marker]:text-meta",
  "[&_.footnotes_::marker]:w-4",
  "[&_.footnotes]:scroll-mt-[calc(theme(spacing.nav)+theme(spacing.inset))]",
  "[&_[id*='user-content-fn']]:scroll-mt-[calc(theme(spacing.nav)+theme(spacing.inset))]",
  "[&_.footnotes_ol]:pl-3.5",
  "[&_.footnotes]:!mt-w12",
  // Footnotes backref link: hide text, show icon
  "[&_.footnotes_.data-footnote-backref]:indent-[-9999px]",
  "[&_.footnotes_.data-footnote-backref]:inline-flex",
  "[&_.footnotes_.data-footnote-backref]:text-solid",
  "[&_.footnotes_.data-footnote-backref]:after:absolute",
  "[&_.footnotes_.data-footnote-backref]:after:top-[0.2em]",
  "[&_.footnotes_.data-footnote-backref]:after:left-[0.3em]",
  "[&_.footnotes_.data-footnote-backref]:after:size-em",
  "[&_.footnotes_.data-footnote-backref]:after:bg-solid",
  "[&_.footnotes_.data-footnote-backref]:after:[mask-size:contain]",
  "[&_.footnotes_.data-footnote-backref]:after:[mask-repeat:no-repeat]",
  "[&_.footnotes_.data-footnote-backref]:after:[mask-position:center]",
  "[&_.footnotes_.data-footnote-backref]:after:[mask-image:url('data:image/svg+xml,%3Csvg%20width%3D%2715%27%20height%3D%2715%27%20viewBox%3D%270%200%2015%2015%27%20fill%3D%27none%27%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%3E%3Cpath%20d%3D%27M4.85355%202.14645C5.04882%202.34171%205.04882%202.65829%204.85355%202.85355L3.70711%204H9C11.4853%204%2013.5%206.01472%2013.5%208.5C13.5%2010.9853%2011.4853%2013%209%2013H5C4.72386%2013%204.5%2012.7761%204.5%2012.5C4.5%2012.2239%204.72386%2012%205%2012H9C10.933%2012%2012.5%2010.433%2012.5%208.5C12.5%206.567%2010.933%205%209%205H3.70711L4.85355%206.14645C5.04882%206.34171%205.04882%206.65829%204.85355%206.85355C4.65829%207.04882%204.34171%207.04882%204.14645%206.85355L2.14645%204.85355C1.95118%204.65829%201.95118%204.34171%202.14645%204.14645L4.14645%202.14645C4.34171%201.95118%204.65829%201.95118%204.85355%202.14645Z%27%20fill%3D%27black%27%20fill-rule%3D%27evenodd%27%20clip-rule%3D%27evenodd%27%2F%3E%3C%2Fsvg%3E')]",
];

// COMPOSE ALL STYLES
export const proseVariants = cva({
  base: USE_CSS_STYLES
    ? ["Prose"]
    : [
        ...proseLayout,
        ...proseInlineElements,
        ...proseLinks,
        ...proseZoomable,
        ...proseHeadings,
        ...proseMedia,
        ...proseCode,
        ...prosePreStyles,
        ...proseBlockquote,
        ...proseListStyles,
        ...proseCalloutStyles,
        ...proseNoteStyles,
        ...proseHrStyles,
        ...proseH4Styles,
        ...proseContactsStyles,
        ...proseFootnotes,
      ],
});

export interface ProseProps
  extends HTMLAttributes<HTMLDivElement>,
    VariantProps<typeof proseVariants> {}

export const MdxProse = ({ className, ...props }: ProseProps) => {
  return <main className={cn(proseVariants({ className }))} {...props} />;
};
